// @numera/db — Supabase client, TypeScript types, and Zod validation schemas

export { createClient, createBrowserClient, createServiceClient } from './client';

export type {
  Database,
  User,
  Lead,
  LeadActivityLog,
  Client,
  ChartOfAccountsCategory,
  EmailNotification,
  DocumentAttachment,
  Transaction,
  Invoice,
  InvoiceLineItem,
  Task,
  Deadline,
  FinancialReport,
  BIRTaxFormRecord,
  DraftEmail,
  // Enum types
  UserRole,
  LeadSource,
  LeadStage,
  BusinessType,
  BIRRegistrationType,
  RevenueBracket,
  ClientStatus,
  TransactionType,
  TransactionStatus,
  EmailNotificationStatus,
  DocumentTypeGuess,
  InvoiceStatus,
  TaskPriority,
  TaskStatus,
  DeadlineType,
  DeadlineStatus,
  ReportType,
  BIRFormNumber,
  TaxFormStatus,
  AccountType,
  NormalBalance,
  GmailConnectionStatus,
  BIRFieldMappingType,
  DraftEmailStatus,
} from './types';

export {
  // Primitive schemas
  uuidSchema,
  isoDateSchema,
  amountSchema,
  tinSchema,
  emailSchema,
  // Enum schemas
  leadSourceSchema,
  leadStageSchema,
  businessTypeSchema,
  birRegistrationTypeSchema,
  revenueBracketSchema,
  clientStatusSchema,
  transactionTypeSchema,
  transactionStatusSchema,
  documentTypeGuessSchema,
  invoiceStatusSchema,
  taskPrioritySchema,
  taskStatusSchema,
  deadlineTypeSchema,
  deadlineStatusSchema,
  reportTypeSchema,
  birFormNumberSchema,
  taxFormStatusSchema,
  accountTypeSchema,
  userRoleSchema,
  // Request body schemas
  contactFormSchema,
  createLeadSchema,
  updateLeadSchema,
  createClientSchema,
  updateClientSchema,
  createTransactionSchema,
  updateTransactionSchema,
  approveTransactionSchema,
  rejectTransactionSchema,
  invoiceLineItemSchema,
  createInvoiceSchema,
  updateInvoiceSchema,
  createTaskSchema,
  updateTaskSchema,
  createDeadlineSchema,
  updateDeadlineSchema,
  generateReportSchema,
  generateNarrativeSchema,
  approveNarrativeSchema,
  prefillBIRFormSchema,
  updateBIRFormSchema,
  exportBIRFormSchema,
  sendEmailSchema,
  classifyEmailSchema,
  dismissEmailSchema,
  connectGmailSchema,
  extractDocumentSchema,
  renderPdfSchema,
  exportToSheetsSchema,
} from './schemas';
